<?php

/**
 * @file
 * Primary module hooks for Menu Reroute module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form\FormState;
use Drupal\menu_reroute\Plugin\Validation\Constraint\RouteExistsConstraint;

/**
 * Implements hook_theme().
 */
function menu_reroute_theme(): array {
  return [
    'dynamic_redirect_route' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for dynamic redirect route templates.
 *
 * Default template: dynamic-redirect-route.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the dynamic redirect route information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_dynamic_redirect_route(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function menu_reroute_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish dynamic redirect routes.
      $storage = \Drupal::entityTypeManager()->getStorage('dynamic_redirect_route');
      $dynamic_redirect_route_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($dynamic_redirect_route_ids) as $dynamic_redirect_route) {
        $dynamic_redirect_route->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize dynamic redirect routes.
      $storage = \Drupal::entityTypeManager()->getStorage('dynamic_redirect_route');
      $dynamic_redirect_route_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($dynamic_redirect_route_ids) as $dynamic_redirect_route) {
        $dynamic_redirect_route->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function menu_reroute_user_predelete(UserInterface $account): void {
  // Delete dynamic redirect routes that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('dynamic_redirect_route');
  $dynamic_redirect_route_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($dynamic_redirect_route_ids)
  );
}



